name = "frihet-api-proxy"
main = "worker.js"
compatibility_date = "2026-01-01"
account_id = "ac385684ceb71bc889f6eb3abade1e32"

[vars]
FRIHET_UPSTREAM_URL = "https://us-central1-frihet-app.cloudfunctions.net/publicApi/api"

[[routes]]
pattern = "api.frihet.io/*"
zone_name = "frihet.io"
